server:
  port: 4372
  tomcat:
    threads:
      min-spare: 30
      max: 1000
    connection-timeout: 5000ms
  ssl:
    enabled: true
    key-store: classpath:salieri.love.jks
    key-store-password: 141315?a

spring:
  servlet:
    multipart:
      max-file-size: 10MB
  datasource:
    username: root
    password: 141315
    url: jdbc:mysql://localhost:3306/music_website?serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /**
  data:
    mongodb:
      uri: mongodb://localhost:27017/comment
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.salieri.entity
logging:
  config: classpath:log4j.xml


